IF COL_LENGTH('dbo.CONVERSATION', 'nickname') IS NULL
    ALTER TABLE dbo.CONVERSATION ADD nickname NVARCHAR(50) NULL;
GO

IF COL_LENGTH('dbo.CONVERSATION', 'topic') IS NULL
    ALTER TABLE dbo.CONVERSATION ADD topic NVARCHAR(255) NULL;
GO

IF COL_LENGTH('dbo.CONVERSATION_MEMBER', 'nickname') IS NULL
    ALTER TABLE dbo.CONVERSATION_MEMBER ADD nickname NVARCHAR(50) NULL;
GO