IF COL_LENGTH('dbo.CONVERSATION_MEMBER', 'is_archived') IS NULL
BEGIN
    ALTER TABLE dbo.CONVERSATION_MEMBER
    ADD is_archived BIT NOT NULL
        CONSTRAINT DF_CONVERSATION_MEMBER_is_archived DEFAULT (0) WITH VALUES;
END;
GO