/* =====================================================================
   Sample seed data for local testing.
   Run AFTER schema.sql.

   NOTE on passwords: the `password` column must hold a BCrypt hash,
   which cannot be generated by plain SQL. All 3 accounts below share
   the password  Password123  encoded with BCrypt (cost 10), generated
   and verified with Python's bcrypt library:

     admin    / Password123   (role = ADMIN)
     alice    / Password123
     bob      / Password123

   Feel free to regenerate your own hash (e.g. via Spring's
   BCryptPasswordEncoder or the `bcrypt` Python package) for anything
   beyond local testing - never reuse this password for a real account.
   ===================================================================== */

USE messaging_db;
GO

DECLARE @bcryptHash VARCHAR(255) = '$2b$10$Z4zvvdiecpZTYnKO/cYV0.AZYwOCsHWppTmfUKfJhlASYohKVh8im';
-- ^ Real BCrypt hash for "Password123", generated and verified with Python's bcrypt
--   library (bcrypt.checkpw confirmed a match). Spring Security's BCryptPasswordEncoder
--   accepts the $2a$/$2b$/$2y$ hash formats interchangeably, so this verifies fine
--   against Spring's PasswordEncoder.matches() too.

INSERT INTO dbo.USERS (username, password, display_name, role, status, is_online, created_at)
VALUES
    ('admin', @bcryptHash, N'Quản trị viên', 'ADMIN', 'ACTIVE', 0, SYSUTCDATETIME()),
    ('alice', @bcryptHash, N'Alice Nguyen',  'USER',  'ACTIVE', 0, SYSUTCDATETIME()),
    ('bob',   @bcryptHash, N'Bob Tran',      'USER',  'ACTIVE', 0, SYSUTCDATETIME());
GO

DECLARE @aliceId BIGINT = (SELECT user_id FROM dbo.USERS WHERE username = 'alice');
DECLARE @bobId   BIGINT = (SELECT user_id FROM dbo.USERS WHERE username = 'bob');

-- Alice and Bob are already friends
INSERT INTO dbo.FRIEND_REQUEST (sender_id, receiver_id, status, created_at)
VALUES (@aliceId, @bobId, 'ACCEPTED', SYSUTCDATETIME());

-- Their private conversation
INSERT INTO dbo.CONVERSATION (type, created_at)
VALUES ('PRIVATE', SYSUTCDATETIME());

DECLARE @convId BIGINT = SCOPE_IDENTITY();

INSERT INTO dbo.CONVERSATION_MEMBER (conversation_id, user_id, role, joined_at)
VALUES
    (@convId, @aliceId, 'MEMBER', SYSUTCDATETIME()),
    (@convId, @bobId,   'MEMBER', SYSUTCDATETIME());

-- A couple of sample messages
INSERT INTO dbo.MESSAGE (conversation_id, sender_id, content, message_type, is_deleted, created_at)
VALUES
    (@convId, @aliceId, N'Chào Bob, dạo này khỏe không?', 'TEXT', 0, DATEADD(MINUTE, -10, SYSUTCDATETIME())),
    (@convId, @bobId,   N'Chào Alice, mình ổn, cảm ơn nhé!', 'TEXT', 0, DATEADD(MINUTE, -8, SYSUTCDATETIME()));

DECLARE @msg1Id BIGINT = (SELECT MIN(message_id) FROM dbo.MESSAGE WHERE conversation_id = @convId);
DECLARE @msg2Id BIGINT = (SELECT MAX(message_id) FROM dbo.MESSAGE WHERE conversation_id = @convId);

-- Message status rows (recipient side) - both already SEEN for the demo
INSERT INTO dbo.MESSAGE_STATUS (message_id, user_id, status, seen_at)
VALUES
    (@msg1Id, @bobId,   'SEEN', DATEADD(MINUTE, -9, SYSUTCDATETIME())),
    (@msg2Id, @aliceId, 'SEEN', DATEADD(MINUTE, -7, SYSUTCDATETIME()));

PRINT 'Seed data inserted: 3 users (admin/alice/bob, password: Password123), 1 friendship, 1 private conversation with 2 messages.';
GO
